### PR TITLE
Make TokenController customizable. Fixes #52

### LINKED ISSUE #52: Customizing Opro::Oauth::TokenController
Hello!

Currently I am writing an article about opro (probably you've seen it on Sitepoint's Trello board). It seems that TokenController is not meant to be customizable, however what I wanted to do is to return a bit more information when presenting a token, for example, some info about a user who is authenticating. https://github.com/opro/opro/blob/ecffe22e777bb9cacfedd55d059a2ca3cb163a05/app/controllers/opro/oauth/token_controller.rb#L15 Like, you know, when authenticating via Twitter we get a pretty big hash of various data about a user apart from token (name, avatar, followers count etc). I could've created some custom controller action and after receiving a token just make individual request there, but that seems a bit cumbersome to me.

Maybe you could recommend something? I'd be very grateful. :)

### PR DESCRIPTION
**Pull request by bodrovis**
This should allow users to tweak `TokenController` or just override `create.json.jbulder` with their own.

### CODE REVIEW

**Comment by schneems** [comment]
Sorry for letting this languish. This seems good. Not sure why builds aren't running on travis https://travis-ci.org/opro/opro/pull_requests investigating.

**Comment by bodrovis** [comment]
Seems like not ENV is set.

**Comment by bodrovis** [comment]
Could it be that hooks are not set?

**Comment by schneems** [comment]
Looks like everything is fine:

**Comment by bodrovis** [comment]
Really strange. Here is config that works for me, but it does not employ Rails... https://github.com/bodrovis/ok_linker/blob/master/.travis.yml

**Comment by bodrovis** [comment]
Also it seems like simplecov https://github.com/opro/opro/blob/master/test/test_helper.rb#L6 is not present in the gemfile, but probably that's not the case

**Comment by schneems** [comment]
It is running on master going to try merging in and see what happens.

**Pull request merged**
